version: '3.8'
services:
  application:
    container_name: zenith-algorithm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - stack

networks:
  stack:
    name: stack
    driver: bridge